name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      namePrefix:
        description: "Prefix for naming"
        required: true
      nameDigits:
        description: "The digits used for unique naming"
        required: true
      tfvarsFile:
        description: "'.tfvars' file with variable values"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.DMW_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.DMW_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.DMW_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.DMW_ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=dmw-lab-${{ github.event.inputs.nameDigits }}-${{ github.event.inputs.namePrefix }}-hub" -backend-config="storage_account_name=${{ github.event.inputs.namePrefix }}cloudshell${{ github.event.inputs.nameDigits }}" -backend-config="container_name=terraform-state" -backend-config="key=terraform.tfstate"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file '${{ github.event.inputs.tfvarsFile }}'
